chore: fix package.json main field
```
import { PostgresMeta } from '@supabase/postgres-meta';
         ^^^^^^^^^^^^
SyntaxError: The requested module '@supabase/postgres-meta' does not provide an export named 'PostgresMeta'
```